# Generated by Django 3.1.1 on 2020-09-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
        ('Book', '0002_auto_20200912_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liber',
            new_name='Book',
        ),
    ]
