# Generated by Django 3.1.1 on 2020-09-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
        ('Book', '0003_auto_20200912_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='viti',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='cart',
        ),
        migrations.AddField(
            model_name='book',
            name='cart',
            field=models.ManyToManyField(to='Cart.Cart'),
        ),
    ]
