# Generated by Django 3.1.1 on 2020-09-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200908_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
